language: node_js
node_js:
  - 13.9.0
before_script:
  - npm install -g fs@0.0.1-security
  - npm install -g json@^9.0.6
  - npm install -g express@4.17.1
  - npm install -g async@3.2.0
  - pip install --user awscli
script:
  - node copyDataFiles.js
  - node loadStatePrayerTimeSitemap.js
  - node loadStateList.js
  - node loadMosqueDetails.js
  - aws s3 rm s3://mosque-finder-aus --quiet --recursive
  - aws s3 sync public/mosque s3://mosque-finder-aus/mosque --quiet --acl public-read
  - aws s3 cp public/index.html s3://mosque-finder-aus --acl public-read --delete
  - aws s3 sync public/nsw s3://mosque-finder-aus/nsw --quiet --acl public-read --delete
  - aws s3 cp public/robots.txt s3://mosque-finder-aus --acl public-read --delete
  - aws s3 sync public/vic s3://mosque-finder-aus/vic --quiet --acl public-read --delete
  - aws s3 sync public/qld s3://mosque-finder-aus/qld --quiet --acl public-read --delete
  - aws s3 sync public/tas s3://mosque-finder-aus/tas --quiet --acl public-read --delete
  - aws s3 sync public/sa s3://mosque-finder-aus/sa --quiet --acl public-read --delete
  - aws s3 sync public/wa s3://mosque-finder-aus/wa --quiet --acl public-read --delete
  - aws s3 sync public/nt s3://mosque-finder-aus/nt --quiet --acl public-read --delete
  - aws s3 sync public/act s3://mosque-finder-aus/act --quiet --acl public-read --delete
  - aws s3 sync public/assets s3://mosque-finder-aus/assets --quiet --acl public-read --delete
  - aws cloudfront create-invalidation --distribution-id E3RII6TTSRX6A1 --paths '/*'
branches:
  only:
  - master