language: node_js
node_js:
  - 13.9.0
before_script:
  - npm install -g fs@0.0.1-security
  - npm install -g json@^9.0.6
  - npm install -g express@4.17.1
  - npm install -g async@3.2.0
  - pip install --user awscli
script:
  - node copyDataFiles.js
  - node loadStatePrayerTimeSitemap.js
  - node loadStateList.js
  - node loadMosqueDetails.js
  - aws s3 sync public/ s3://mosque-finder-aus --quiet --acl public-read --delete
  - aws cloudfront create-invalidation --distribution-id E3RII6TTSRX6A1 --paths '/*'
branches:
  only:
  - master